// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QAHe0GgPSmM5O2bJf8_XZEzgCVBx_Ps',
    appId: '1:346276141245:web:a3e27233a20eda4fb0bfd4',
    messagingSenderId: '346276141245',
    projectId: 'todolist-d06e6',
    authDomain: 'todolist-d06e6.firebaseapp.com',
    storageBucket: 'todolist-d06e6.appspot.com',
    measurementId: 'G-TNZQ6FGHLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xWNgag9V8hP40EMCk8ziKR7N0IOQvc0',
    appId: '1:346276141245:android:cbc26e3d115b56ddb0bfd4',
    messagingSenderId: '346276141245',
    projectId: 'todolist-d06e6',
    storageBucket: 'todolist-d06e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC460A5a8VEbXDF3zjylAya9J4fLpI8aaM',
    appId: '1:346276141245:ios:ffa785373089998db0bfd4',
    messagingSenderId: '346276141245',
    projectId: 'todolist-d06e6',
    storageBucket: 'todolist-d06e6.appspot.com',
    iosBundleId: 'com.example.todofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC460A5a8VEbXDF3zjylAya9J4fLpI8aaM',
    appId: '1:346276141245:ios:cfd9a1913f074e63b0bfd4',
    messagingSenderId: '346276141245',
    projectId: 'todolist-d06e6',
    storageBucket: 'todolist-d06e6.appspot.com',
    iosBundleId: 'com.example.todofirebase.RunnerTests',
  );
}
